# Generated by Django 4.2 on 2023-06-17 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data9', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='Issued_roll_no',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
